[package]
name = "xvg-cli"
version = "1.0.0"
edition = "2021"
[dependencies]
xvg-core = { path = "../xvg-core", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
usvg = { version = "0.36", default-features = false, features = ["text"] }
tiny-skia = "0.11"
tiny-skia-path = "0.11"
image = "0.24"
kurbo = "0.9"