[workspace]
members = [
    "xvg-runtime",
    "xvg-core",
    "xvg-cli", 
    "xvg-py",
    "xvg-ffi",
    "xvg-wasm",
    "xvg-thumbnail-handler",
    "xvg-desktop/src-tauri",
]
exclude = [
]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["xvg-team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/amplifaiui/xvg-tesseract" 