// Auto-generated by cbindgen. Do not edit by hand.


#ifndef XVG_PLUGIN_H
#define XVG_PLUGIN_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

typedef struct Vec_u8 Vec_u8;

typedef struct xvg_bitmap {
  uint32_t width;
  uint32_t height;
  uint32_t stride;
  uint32_t format;
  uint8_t *rgba;
  size_t len;
} xvg_bitmap;

typedef struct xvg_handle {
  struct Vec_u8 bytes;
} xvg_handle;

typedef struct xvg_mesh {
  float *vertices;
  uint32_t vertex_count;
  uint32_t *indices;
  uint32_t index_count;
} xvg_mesh;

uint32_t xvg_version(void);

uint64_t xvg_features(void);

void xvg_free(void *p);

void xvg_bitmap_free(struct xvg_bitmap *bmp);

int xvg_open(const uint8_t *bytes, size_t len, struct xvg_handle **out);

void xvg_close(struct xvg_handle *h);

int xvg_render(struct xvg_handle *h, unsigned int w, unsigned int hgt, struct xvg_bitmap *out_bmp);

int xvg_extract(struct xvg_handle *h, const char *fmt, uint8_t **out, size_t *out_len);

void xvg_mesh_free(struct xvg_mesh *m);

int xvg_extrude_mesh(struct xvg_handle *h, float depth, struct xvg_mesh *out);

#endif /* XVG_PLUGIN_H */
